name: Generate documentation

on:
  push:
    branches:
      - '*'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdbook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
          mv mdbook /usr/local/bin
      - name: Build Rust documentation
        working-directory: ./framework/docs
        run: |
          mdbook build
          mkdir ../../docs
          mv book/* ../../docs
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Build Python documentation
        working-directory: ./wrappers/python
        run: |
          pip install -r requirements-dev.txt
          ./generate_documentation.py
          mkdir ../../docs/python
          mv docs/* ../../docs/python
