name: Publish documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install mdbook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz
          mv mdbook /usr/local/bin
      - name: Build Rust documentation
        working-directory: ./docs
        run: |
          mdbook build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/book/'
      - name: Deploy to GitHub Pages
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
        id: deployment
        uses: actions/deploy-pages@v4
